config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
		resources :stores, only: [:index, :create, :new]
	end
	resources :stores , only: [:show, :edit, :update, :destroy] do
		get :sale, to: "stores#sale"
		resources :products, only: [:index, :create, :new]
		member do
			get :assignment, to: "products#assignment"
			post :assign, to: "products#assign"
			post :unassign, to: "products#unassign"
		end
	end
	resources :products , only: [:show, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	#belongs_to :store

	scope :available, ->{ where(is_online: true) }
	scope :over_than, ->(x){ where(["price > ?", x]) }


	has_many :ware_houses
  has_many :stores, through: :ware_houses

  mount_uploader :image, ImageUploader

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  #has_many :products

  has_many :ware_houses
  has_many :products, through: :ware_houses


end

app/models/user.rb
class User < ApplicationRecord
	has_many :stores
end

app/models/ware_house.rb
class WareHouse < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :find_product, only: [:show, :edit, :update, :destroy, :assignment, :assign, :unassign]
	
	def index
		@store = Store.find(params[:store_id])
		@products = @store.products

		#render action: "edit" #去找edit.html
	end

	def new
		@store = Store.find(params[:store_id])
		@product = Product.new
	end

	def create
		@store = Store.find(params[:store_id])
		@product = Product.new(clean_product_params) 


      if @product.save && WareHouse.create( :store_id => @store.id, :product_id => @product.id )
       	#debugger
        redirect_to store_products_path(@store), notice: "new product!"
      else
        #render :new, notice: "WRONG!"
        redirect_to new_store_product_path(@store), notice: "WRONG!"
        #用redirect_to 不會保留剛剛打好的資料 會惹怒民眾！  (edit同理
      end
	end

	def edit
		#find_
	end

	def update
		#find_

		if @product.update(clean_product_params)
			redirect_to store_products_path(@product.stores.first), notice: "update product!"
    else
      render :edit, notice: "WRONG!"
    end
	end

	def destroy
		#find_
		@product.destroy
		redirect_to users_path, notice: "destroy product!"
	end
	def show
		#find_
	end
	#---------------------------------
	def assignment
		@stores = @product.stores
		@not_in_stores = Store.where.not("id IN (?)", @stores.ids)
		# byebug
		# @warehouses = WareHouse.where( "product_id == ?", @product.id )
		# @not_in_warehouses = WareHouse.where( "product_id != ?", @product.id )

		# @in_store = []
		# @assign_stores = []

		# @warehouses.each do |w|
		# 	@in_store << w.store_id
		
		# end

		# @not_in_warehouses.each do |niw|
		# 	@assign_stores << niw.store_id unless ( @in_store.include? niw.store_id and @assign_stores.include? niw.store_id )
		
		# end

	end
	def assign
		
		@store = Store.find(params[:format])
		# debugger
		if WareHouse.create( :store_id => @store.id, :product_id => @product.id )
			redirect_to assignment_store_path(@product), notice: "assign success!"
		end

	end
	def unassign
		
		@store = Store.find(params[:format])
		#@w = WareHouse.where(["store_id = ? and product_id = ?", @store.id, @product.id]).limit(1)
		#debugger
		if WareHouse.where(["store_id = ? and product_id = ?", @store.id, @product.id]).limit(1).destroy_all
			redirect_to assignment_store_path(@product), notice: "unassign success!"
		end

	end

#---------------------------------
	private #######

	def clean_product_params #params[:candidate]
		clean_params = params.require(:product).permit(:title, :description, :price, :store_id, :image)
	end

	def find_product
		@product = Product.find_by(id: params[:id])
		#redirect_to stores_path unless @store
	end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	before_action :find_store, only: [:show, :edit, :update, :destroy]
	
	def index
		@user = User.find(params[:user_id])
		@stores = @user.stores

		#render action: "edit" #去找edit.html
	end

	def new
		@user = User.find(params[:user_id])
		@store = Store.new
	end

	def create
		@user = User.find(params[:user_id])
		@store = Store.new(clean_store_params) 


      if @store.save
       	#debugger
        redirect_to user_stores_path(@user), notice: "new store!"
      else
        #render :new, notice: "WRONG!"
        redirect_to new_user_store_path(@user), notice: "WRONG!"
        #用redirect_to 不會保留剛剛打好的資料 會惹怒民眾！  (edit同理
      end
	end

	def edit
		#find_cand
	end

	def update
		#find_cand

		if @store.update(clean_store_params)
			redirect_to user_stores_path(@store.user), notice: "update store!"

    else
      render :edit, notice: "WRONG!"
    end
	end

	def destroy
		#find_cand
		@store.destroy
		redirect_to users_path, notice: "destroy store!"
	end
	def show
		#find_cand
	end

	def sale
		
	end

	private #######

	def clean_store_params #params[:candidate]
		clean_params = params.require(:store).permit(:name, :tel, :address, :user_id)
	end

	def find_store
		@store = Store.find_by(id: params[:id])
		 #redirect_to stores_path unless @store
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [:show, :edit, :update, :destroy]
	
	def index
		@users = User.all
		#render action: "edit" #去找edit.html
	end

	def new
		@user = User.new
	end
	def create
		@user = User.new(clean_user_params) 

      if @user.save
        redirect_to users_path, notice: "new user!"
      else
        render :new, notice: "WRONG!"
        #redirect_to new_candidate_path 
        #用redirect_to 不會保留剛剛打好的資料 會惹怒民眾！  (edit同理
      end
	end

	def edit
		#find_cand
	end

	def update
		#find_cand

		if @user.update(clean_user_params)
			redirect_to users_path, notice: "update user!"
    else
        render :edit, notice: "WRONG!"
    end
	end

	def destroy
		#find_cand
		@user.destroy
		redirect_to users_path, notice: "destroy user!"
	end
	def show
		#find_cand
	end

	private #######

	def clean_user_params #params[:candidate]
		clean_params = params.require(:user).permit(:name, :tel, :email)
	end

	def find_user
		@user = User.find_by(id: params[:id])
		redirect_to users_path unless @user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="container">
  <%= flash[:notice] %>
  	<%= yield %>
  </div>
  
    
  </body>
</html>

app/views/products/_product.html.erb
  <div class="item well">
    
    <div class="image_size">
    <% if product.image.nil?  %>
        <img class="img-rounded" src="http://fakeimg.pl/250x100/" alt="no pic!"> 
    <% else  %>
        <%= image_tag product.image %>
    <% end %>
    </div>
    <span class="details hidden">
        
    <table class="table">
        <tr>
          <td>ID: <%= product.id %></td>
        </tr>
        <tr>
          <td>Title: <%= product.title %></td>
        </tr>
        <tr>
            <td>Price: NTD <%= product.price %> </td>
        </tr>
        <tr>
          <td>Description: <%= product.description %></td>
        </tr>
    </table>
        

    </span>

    <p class="title"> <h3><%= product.title %></h3> </p>
    <p class="price">NTD <%= product.price %> </p>
    <p> 
    <%= link_to "assign", assignment_store_path(product), :target => "_blank", class:"btn btn-success" %>
    <a class="btn btn-primary" href="">View details</a>
    </p>
    <p>
    <%= link_to "edit", edit_product_path(product), class:"btn btn-warning" %>
    <%= link_to "destroy", product_path(product), method: "delete", data: { confirm: "sure?" }, class:"btn btn-danger" %>
    </p>


  </div>

app/views/products/assignment.html.erb
<h1>Product: <%= @product.title%>(ID: <%= @product.id%>)</h1>

<div class="row">

<div class="col-sm-6">
<table class="table table table-condensed">
  <thead>
    <tr>
    <caption><h3> <%= @product.title %> are in ...</h3></caption>
        <th>#</th>
        <th>Store</th>
    </tr>
  </thead>
  <tbody>
  <%  @stores.each do |w| %>
    <tr>
      <td> <%= w.id %> </td>
      <td> <%= w.name %> </td>
      <td> <%= link_to "unassign", unassign_store_path(@product, w.id), method: "post", class:"btn btn-danger" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>

<div class="col-sm-6">
<table class="table table table-condensed">
  <thead>
  <tr>
  <caption><h3> Assign <%= @product.title %> to other store...</h3></caption>
        <th>#</th>
        <th>Store</th>
    </tr>
  </thead>
  <tbody>
  <%  @not_in_stores.each do |nis| %>
    <tr>
      <td> <%= nis.id %> </td>
      <td> <%= nis.name %> </td>
      <td> <%= link_to "assign", assign_store_path(@product, nis.id), method: "post", class:"btn btn-success" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>

</div>

app/views/products/edit.html.erb
<h1>Edit product  </h1>

<%= form_for @product do |f| %>

<div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title , class:"form-control" %> 
</div>
<div class="form-group">
	<%= f.label :description, "Description" %>
  <%= f.text_field :description , class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :price, "Price" %>
  <%= f.text_field :price , class:"form-control" %>
</div>
<div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image %>
    <% end %>
</div>

  <%= f.submit class:"btn btn-warning" %>
	
<% end %>

app/views/products/index.html.erb
<div class="page-header">
    <h1>List of Product (<%= @store.name%> / <%= @store.id%>) </h1>   
</div>

<p>
  <%= link_to "new product", new_store_product_path(@store), class:"btn btn-info" %>
  <%= link_to "I want to play a game!", store_sale_path(@store), :target => "_blank", class:"btn btn-danger btn-lg" %>
</p>

    <%= render partial: "product", collection: @products %>

<!-- 燈箱 -->
  <div class="mask">
    <div class="dialog-box well">
        <a class="close">&times;</a>
        <div class="content"></div>
    </div>
  </div>
<!-- 燈箱 -->

app/views/products/new.html.erb
<h1>New Product (<%= @store.name%>)</h1>


<%= form_for [@store, @product] do |f| %>

<div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title , class:"form-control" %>
</div>
<div class="form-group">
	<%= f.label :description, "Description" %>
  <%= f.text_field :description , class:"form-control" %>
</div>
<div class="form-group">
	<%= f.label :price, "Price" %>
  <%= f.text_field :price , class:"form-control" %>
</div>
<div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
</div>



  <%= f.hidden_field :store_id, :value => @store.id %> <br />

  <%= f.submit class:"btn btn-warning" %>

<%= link_to 'back', store_products_path(@store), class:"btn btn-info"%>
	
<% end %>

app/views/stores/_form.html.erb
	<%= form_for store do |f| %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name %> <br />

 	<%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %> <br /> 

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %> <br />


  <%= f.submit class:"btn btn-warning" %>


<%= link_to 'back', user_stores_path(user), class:"btn btn-info"%>
	
<% end %>

app/views/stores/_store.html.erb
<tr>

<td> <%= store.id %></td>
<td> <%= store.name %></td>
<td> <%= store.tel %></td>
<td> <%= store.address %></td>
<td> <%= store.products.count %></td>
<td> <%= link_to "Visit !", store_products_path(store), :target => "_blank", class:"btn btn-success" %> </td>
<td> <%= link_to "edit", edit_store_path(store), class:"btn btn-warning" %> </td>
<td> <%= link_to "destroy", store_path(store), method: "delete", data: { confirm: "sure?" }, class:"btn btn-danger" %></td>



</tr>

app/views/stores/edit.html.erb
<h1>Edit Store  </h1>

<%= form_for @store do |f| %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name %> <br />

 	<%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %> <br /> 

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %> <br />

  <%= f.submit class:"btn btn-warning btn-submit" %>
	
<% end %>

app/views/stores/index.html.erb
<div class="page-header">
    <h1>List of Stores (<%= @user.name%> / <%= @user.id%>) </h1>      
</div>
<%= link_to "<< user list", users_path, class:"btn btn-warning" %>
<%= link_to "new store", new_user_store_path(@user), class:"btn btn-info" %>

  <table class="table">
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Tel</td>
        <td>Address</td>
        <td>Product count</td>

      </tr>
    </thead>
    <tbody>

    <%= render partial: "store", collection: @stores %>

<!--     <% @stores.each do |store| %>
      <%= render partial: 'store', locals: { store: store } %>
      <%= render 'store', store: store %>
    <% end %> -->



    </tbody>
  </table>

app/views/stores/new.html.erb
<h1>New Store (<%= @user.name%>)</h1>


<%= form_for [@user, @store] do |f| %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name %> <br />

 	<%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %> <br /> 

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %> <br />

  <%= f.hidden_field :user_id, :value => @user.id %> <br />

  <%= f.submit class:"btn btn-warning" %>

<%= link_to 'back', user_stores_path(@user), class:"btn btn-info"%>
	
<% end %>

app/views/stores/sale.html.erb
<div class="wrap">

    <div class="lottery-nums"></div>
    <div class="lottery-result">開獎號碼: <span></span></div>

    <p>
      <button class="btn-lottery">開獎</button>
      <button class="reset">重設</button>
    </p>
    <hr>
    <p class="record">
      開獎紀錄:<span></span>
    </p>  

  </div>
  

app/views/users/_form.html.erb
	<%= form_for user do |f| %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name %> <br />

 	<%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %> <br /> 

  <%= f.label :email, "Email" %>
  <%= f.text_field :email %> <br />


  <%= f.submit class:"btn btn-warning" %>


<%= link_to 'back', users_path, class:"btn btn-info"%>
	
<% end %>

app/views/users/_user.html.erb
<tr>

<td> <%= user.id %></td>
<td> <%= user.name %></td>
<td> <%= user.tel %></td>
<td> <%= user.email %></td>
<td> <%= user.stores.ids %></td>
<td> <%= link_to "store list", user_stores_path(user), class:"btn btn-success" %> </td>
<td> <%= link_to "edit", edit_user_path(user), class:"btn btn-warning" %> </td>
<td> <%= link_to "destroy", user_path(user) , method: "delete", data: { confirm: "sure?" }, class:"btn btn-danger" %></td>

</tr>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div class="page-header">
<h1>List of Users</h1>
</div>

<%= link_to "new user", new_user_path, class:"btn btn-info" %>

  <table class="table">
    <thead>
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Tel</td>
        <td>Email</td>
        <td>Store</td>
      </tr>
    </thead>
    <tbody>

     <%= render partial: "user", collection: @users %>

    </tbody>
  </table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>